# email
mail:
  domain: lp@gmail.com
# info logging demo
#info:
  #id: ${spring.application.name}
#logging:
  #level:
    #org.springframework.security: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 720000
        readTimeout: 720000
        loggerLevel: basic
